### ISSUE TITLE
Feature Request: Explore Archive Files Recursively

### ISSUE THREAD

**Issue by mHuseyin0** [ndtoan96/ouch.yazi#10]
It would be good if we were able to see the content of archive files inside of a parent archive file. [xarchiver](https://github.com/ib/xarchiver) has this functionality but I could not find any CLI tool having that.

**Comment by ndtoan96** [comment]
You mean nested archive? I don't think people would normally put an archive inside another archive, except .tar.gz and the like but ouch already supports them.

**Comment by mHuseyin0** [comment]
Yes I meant nested archive files. I needed to explore a .zip inside a .zip and didn't think it could be supported for tar.gz. Nevertheless, being able to do it for all archives would be good I think.

**Comment by ndtoan96** [comment]
Well, this plugin is just a simple wrapper of the `ouch` program and your use case is not supported by `ouch` itself. I may be able to work around it somehow but I don't think the case is common enough to be worth the effort.

**Comment by mHuseyin0** [comment]
Understandable, have a great day.
