### ISSUE TITLE
ui.Paragraph and ui.ListItem deprecated

### ISSUE THREAD

**Issue by rafi** [ndtoan96/ouch.yazi#11]
The `ui.Paragraph` and `ui.ListItem` elements have been deprecated in Yazi v0.4.
Please use the new `ui.Text` instead, see https://github.com/sxyazi/yazi/pull/1776 for details.

**Comment by ndtoan96** [comment]
Thanks, fixed in 7ea717a3f3b4543c97a92779aecc814263642be7.
