### ISSUE TITLE
Feature Request: Add commands to unpack an archive

### ISSUE THREAD

**Issue by fdw** [ndtoan96/ouch.yazi#5]
It would be really helpful if there were some command to unpack a selected archive, but unfortunately, I haven't found one.

**Comment by ndtoan96** [comment]
Yazi already had that by default. Although it uses `unar` so you have to had `unar` installed. You can change it to `ouch` or any other archive tool (for example `7z`) by modifying the `yazi.toml` file. Press `o` to extract, or press `shift-o` to select between them.

```toml
[opener]
extract = [
	{ run = 'ouch d -y "%*"', desc = "Extract here with ouch" },
	{ run = '7z x "%*"', desc = "Extract here with 7z" },
]
```

**Comment by fdw** [comment]
Sorry, I didn't think it was that easy. Thank you!
