### ISSUE TITLE
Support compressing selected files

### ISSUE THREAD

**Issue by uncenter** [ndtoan96/ouch.yazi#6]
Similar to https://github.com/KKV9/archive.yazi, would be nice to do this with `ouch` instead.

**Comment by ndtoan96** [comment]
That's an interesting idea. I'll look into it when I had time. I may add the functionality to this plugin or make a new one where users can configure how they like to compress the files. Or maybe contribute to the archive.yazi plugin if that is feasible with their code.

**Comment by ndtoan96** [comment]
I decided to add compress command to this plugin, since `ouch` can handle almost all formats with zero configuration needed.

I have implemented it in the latest main branch. Can you try it out and give some feedback.

**Comment by uncenter** [comment]
Awesome it works great! Thank you!

**Comment by AnirudhG07** [comment]
How do you use this? like archive.yazi, I want the input box opener. in the readme I coudnt find any reference for this

**Comment by uncenter** [comment]
> How do you use this? like archive.yazi, I want the input box opener. in the readme I coudnt find any reference for this

Uhh it's right here? https://github.com/ndtoan96/ouch.yazi#compression

**Comment by AnirudhG07** [comment]
I didnt read "you can change it however you want" I assumed it was just zips. SO sorry and Thanks!

**Comment by AnirudhG07** [comment]
Great work dude, this is much better and exactly what I wanted!!!
