### ISSUE TITLE
[question] absolute noob starting yazi can't handle compress

### ISSUE THREAD

**Issue by 573** [ndtoan96/ouch.yazi#9]
I'm incapable to make compress part running, here is what I did so far:
* select file to compress in yazi (`v`)
* hit `C`
* hit `w` to see what happens

There is `Run micro plugin 'ouch'` shown and `2 left` in the status line shown.
When I hit `q` after a while I'm asked if ouch process ought to be closed.

**Comment by ndtoan96** [comment]
Are your files large? Have you tried with small files? Instead of `v`, have you tried `space` for selection?

**Comment by 573** [comment]
Yes, with a javascript file and `space` then `C` I see the same effect.

**Comment by 573** [comment]
Reinstalled, it works now.
